### ISSUE TITLE
How to compile for macOS?

### ISSUE THREAD

**Issue by ryahpalma** [lkytus/2dgame#2]
I looked README and found no way to compile that game on Darwin 
When I try to compile, `make` command give this error:
```
make: *** [all] Error 1
```

**Comment by lkytus** [comment]
It seems like you don't the compiler.
Try use GCC or Clang, and create a link "c99" to the compiler, if you don't have this executable.
Also, check for dependencies. You need to install freeglut and openal-soft. And you need OpenGL 3.3 compatible drivers.

Sorry for late response.

**Comment by ryahpalma** [comment]
Works like a charm! thank you :smile:
